[workspace]
resolver = "3"
members = [
    "colony_protocol",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Cemonix gittlermilan@seznam.cz"]
license = "GPL-3.0-or-later"
repository = "https://github.com/Cemonix/ColonyProtocol"

[workspace.dependencies]
